install:
    - ps: |
        # Here we nstall platyPS to the worker machine form the gallery
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module platyPS -Force
        Import-Module platyPS

build_script:
    - ps: |
        New-ExternalHelp -Path ./docs/ -OutputPath ./en-US/ -Force
test_script:
    - ps: |
        Import-Module ./Greet.psm1 -Force
        Update-MarkdownHelp -Path ./docs
        $diff = git diff
        if ($diff) {
            throw "Help is not up-to-date: $diff"
        }
